polycand_metric:
  class_path: comet_poly.models.PolyCandMetric
  init_args:
    nr_frozen_epochs: 0.3
    keep_embeddings_frozen: True
    optimizer: AdamW
    encoder_learning_rate: 1.0e-06
    learning_rate: 1.5e-05
    layerwise_decay: 0.95
    encoder_model: XLM-RoBERTa
    pretrained_model: xlm-roberta-large
    pool: avg
    layer: mix
    layer_transformation: sparsemax
    layer_norm: False
    loss: mse
    dropout: 0.1
    batch_size: 8
    train_data: 
      - data/csv/train_same_sim.csv
    validation_data: 
      - data/csv/dev_same_sim.csv
    hidden_sizes:
      - 2048
      - 1024
    activations: Tanh
    additional_translation_in: [True, True, True, True, True]
    additional_score_in: [False, False, False, False, False]
    additional_score_out: [False, False, False, False, False]
    
trainer: ../../trainer_half.yaml
early_stopping: ../../early_stopping.yaml
model_checkpoint: ../../model_checkpoint.yaml