class_path: pytorch_lightning.callbacks.early_stopping.EarlyStopping
init_args:
  monitor: val_mse
  min_delta: 0.
  patience: 8
  verbose: False
  mode: min
  strict: True
  check_finite: True
  stopping_threshold: null
  divergence_threshold: null
  check_on_train_epoch_end: False
