class_path: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
init_args:
  dirpath: null
  filename: '{epoch}-{step}-{val_mse:.5f}'
  monitor: val_mse
  verbose: True
  save_last: False
  save_top_k: -1
  mode: min
  auto_insert_metric_name: True
  save_weights_only: True
  every_n_train_steps: 1250
  train_time_interval: null
  every_n_epochs: null
  save_on_train_epoch_end: null
